# Generated by Django 3.1.4 on 2021-01-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='pay', max_length=100)),
                ('tasks', models.TextField(verbose_name='description')),
                ('task_type', models.CharField(choices=[('Important', 'Important'), ('Very Important', 'Very important')], max_length=100)),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
