# Generated by Django 3.1.4 on 2021-01-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='enddate',
            field=models.DateTimeField(),
        ),
    ]
